// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicShop.Migrator;

#nullable disable

namespace MusicShop.Migrator.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    [Migration("20230822160635_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicShop.Domain.Models.MusicalInstrument.MusicalInstrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreationCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstrumentModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InstrumentTypeId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OfferId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentTypeId");

                    b.HasIndex("OfferId");

                    b.ToTable("MusicalInstrument");
                });

            modelBuilder.Entity("MusicShop.Domain.Models.MusicalInstrument.MusicalInstrumentType.InstrumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InstrumentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("InstrumentType");
                });

            modelBuilder.Entity("MusicShop.Domain.Models.Offer.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<int>("OfferState")
                        .HasColumnType("int");

                    b.Property<double>("RequirePrice")
                        .HasColumnType("float");

                    b.Property<Guid?>("UserId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Offer");
                });

            modelBuilder.Entity("MusicShop.Domain.Models.Offer.OfferCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("OfferCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OfferId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OfferCategoryId");

                    b.HasIndex("OfferId");

                    b.ToTable("OfferCategory");
                });

            modelBuilder.Entity("MusicShop.Domain.Models.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("RegistratedIn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MusicShop.Domain.Models.MusicalInstrument.MusicalInstrument", b =>
                {
                    b.HasOne("MusicShop.Domain.Models.MusicalInstrument.MusicalInstrumentType.InstrumentType", "InstrumentType")
                        .WithMany("MusicalInstruments")
                        .HasForeignKey("InstrumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicShop.Domain.Models.Offer.Offer", null)
                        .WithMany("InstrumentsToOffer")
                        .HasForeignKey("OfferId");

                    b.Navigation("InstrumentType");
                });

            modelBuilder.Entity("MusicShop.Domain.Models.MusicalInstrument.MusicalInstrumentType.InstrumentType", b =>
                {
                    b.HasOne("MusicShop.Domain.Models.MusicalInstrument.MusicalInstrumentType.InstrumentType", null)
                        .WithMany("SubTypes")
                        .HasForeignKey("InstrumentTypeId");

                    b.HasOne("MusicShop.Domain.Models.User.User", null)
                        .WithMany("MusicalSpecialization")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("MusicShop.Domain.Models.Offer.Offer", b =>
                {
                    b.HasOne("MusicShop.Domain.Models.User.User", "User")
                        .WithMany("Offers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicShop.Domain.Models.Offer.OfferCategory", b =>
                {
                    b.HasOne("MusicShop.Domain.Models.Offer.OfferCategory", null)
                        .WithMany("Categories")
                        .HasForeignKey("OfferCategoryId");

                    b.HasOne("MusicShop.Domain.Models.Offer.Offer", "Offer")
                        .WithMany("OfferCategories")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("MusicShop.Domain.Models.MusicalInstrument.MusicalInstrumentType.InstrumentType", b =>
                {
                    b.Navigation("MusicalInstruments");

                    b.Navigation("SubTypes");
                });

            modelBuilder.Entity("MusicShop.Domain.Models.Offer.Offer", b =>
                {
                    b.Navigation("InstrumentsToOffer");

                    b.Navigation("OfferCategories");
                });

            modelBuilder.Entity("MusicShop.Domain.Models.Offer.OfferCategory", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("MusicShop.Domain.Models.User.User", b =>
                {
                    b.Navigation("MusicalSpecialization");

                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
